### ISSUE TITLE
Use only one Travis job for code coverage

### ISSUE THREAD

**Issue by egpbos** [NLeSC/mcfly#158]
Right now, all Travis jobs do the code coverage checks:

```yml
script: 
  - nosetests --with-coverage --cover-package=mcfly

after_script:
  - "pip install scrutinizer-ocular"
  - "ocular"
```

This is not necessary, since the code does not change between jobs (and Scrutinizer only reports about the last check anyway). Leaving it out of the regular test jobs and adding an additional job dedicated to code coverage would reduce run time of the regular test jobs as well, giving faster CI feedback.
